package main

import (
	"math"
	"strconv"
	"testing"

	"github.com/kartikparsoya-eng/go-ivm/engine"
)

// Oracle vectors generated by running the REAL TS h64(rowIDString(...))
// against mono's hash.ts + row-key.ts + row-set-signature.ts via tsx.
// See gen-sig-vectors.mts in the mono tree.

type sigVector struct {
	desc     string
	table    string
	rowKey   map[string]interface{}
	rowIDStr string
	sigHex   string
}

var sigVectors = []sigVector{
	{"simple string PK", "t", map[string]interface{}{"id": "abc"}, `["","t","id","abc"]`, "1577071b99a74425"},
	{"multi-PK unsorted", "t", map[string]interface{}{"b": "2", "a": "1"}, `["","t","a","1","b","2"]`, "b2f7cdb96bebff9e"},
	{"multi-PK sorted", "t", map[string]interface{}{"a": "1", "b": "2"}, `["","t","a","1","b","2"]`, "b2f7cdb96bebff9e"},
	{"integer as float", "t", map[string]interface{}{"id": float64(42)}, `["","t","id",42]`, "d2fbe8ba11d70c7c"},
	{"negative int", "t", map[string]interface{}{"id": float64(-5)}, `["","t","id",-5]`, "fab69850560f17f"},
	{"zero", "t", map[string]interface{}{"id": float64(0)}, `["","t","id",0]`, "ec167baa034baaa"},
	{"negative zero", "t", map[string]interface{}{"id": math.Copysign(0, -1)}, `["","t","id",0]`, "ec167baa034baaa"},
	{"float pi", "t", map[string]interface{}{"id": float64(3.14)}, `["","t","id",3.14]`, "a68a8427f24d2827"},
	{"large exponent", "t", map[string]interface{}{"id": float64(1e21)}, `["","t","id",1e+21]`, "2a5f5310aae7a5c8"},
	{"small exponent", "t", map[string]interface{}{"id": float64(1e-7)}, `["","t","id",1e-7]`, "7c9de0d424128b5d"},
	{"boolean true", "t", map[string]interface{}{"flag": true}, `["","t","flag",true]`, "707ae21b52a8981b"},
	{"boolean false", "t", map[string]interface{}{"flag": false}, `["","t","flag",false]`, "6e0f093bc1778fa5"},
	{"null value", "t", map[string]interface{}{"id": nil}, `["","t","id",null]`, "7b41f95385716dec"},
	{"empty string PK", "t", map[string]interface{}{"id": ""}, `["","t","id",""]`, "869aade422229bf"},
	{"string with quote", "t", map[string]interface{}{"id": `a"b`}, `["","t","id","a\"b"]`, "54f2ce1a3fc2db6"},
	{"string with backslash", "t", map[string]interface{}{"id": `a\b`}, `["","t","id","a\\b"]`, "34ca6af406fe78a9"},
	{"string with newline", "t", map[string]interface{}{"id": "a\nb"}, `["","t","id","a\nb"]`, "a2c35a363062aed5"},
	{"string with control char", "t", map[string]interface{}{"id": "a\x00b"}, `["","t","id","a\u0000b"]`, "b3fad11203b6b653"},
	{"different table same key", "users", map[string]interface{}{"id": "abc"}, `["","users","id","abc"]`, "25cc2d9476d778ba"},
	{"long table name", "app_123.conversations_paginated_v3", map[string]interface{}{"id": "x"}, `["","app_123.conversations_paginated_v3","id","x"]`, "a363541661a28132"},
	{"multi-PK mixed types", "t", map[string]interface{}{"name": "Alice", "age": float64(30), "active": true}, `["","t","active",true,"age",30,"name","Alice"]`, "e6a5f6cf99a9829d"},
	{"UTF-16 column order", "t", map[string]interface{}{"\uE000": "bmp", "\U00010000": "astral"}, "[\"\",\"t\",\"𐀀\",\"astral\",\"\",\"bmp\"]", "66a3e94c2489b070"},
}

func TestRowIDString(t *testing.T) {
	for _, v := range sigVectors {
		t.Run(v.desc, func(t *testing.T) {
			got := rowIDString(v.table, v.rowKey)
			if got != v.rowIDStr {
				t.Fatalf("rowIDString(%q, %v) = %q, want %q", v.table, v.rowKey, got, v.rowIDStr)
			}
		})
	}
}

func TestH64(t *testing.T) {
	for _, v := range sigVectors {
		t.Run(v.desc, func(t *testing.T) {
			got := h64(v.rowIDStr)
			want, err := strconv.ParseUint(v.sigHex, 16, 64)
			if err != nil {
				t.Fatalf("bad oracle hex %q: %v", v.sigHex, err)
			}
			if got != want {
				t.Fatalf("h64(%q) = %x, want %x", v.rowIDStr, got, want)
			}
		})
	}
}

func TestRowIDSignatureUnit(t *testing.T) {
	for _, v := range sigVectors {
		t.Run(v.desc, func(t *testing.T) {
			got := h64(rowIDString(v.table, v.rowKey))
			want, _ := strconv.ParseUint(v.sigHex, 16, 64)
			if got != want {
				t.Fatalf("sigUnit(%q,%v) = %x, want %x", v.table, v.rowKey, got, want)
			}
		})
	}
}

func TestNegativeZeroMatchesZero(t *testing.T) {
	pos := h64(rowIDString("t", map[string]interface{}{"id": float64(0)}))
	neg := h64(rowIDString("t", map[string]interface{}{"id": math.Copysign(0, -1)}))
	if pos != neg {
		t.Fatalf("sig(0)=%x != sig(-0)=%x — Go must match JS String(-0)==='0'", pos, neg)
	}
}

func TestColumnSortingMatchesTS(t *testing.T) {
	unsorted := h64(rowIDString("t", map[string]interface{}{"b": "2", "a": "1"}))
	sorted := h64(rowIDString("t", map[string]interface{}{"a": "1", "b": "2"}))
	if unsorted != sorted {
		t.Fatalf("column sort mismatch: unsorted=%x != sorted=%x", unsorted, sorted)
	}
}

func TestRowSigAccumulatorIncludesZeroDelta(t *testing.T) {
	acc := NewRowSigAccumulator()
	rowKey := map[string]interface{}{"id": "same"}
	acc.accumulate(engine.RowChange{Type: engine.RowChangeAdd, QueryID: "q1", Table: "t", RowKey: rowKey})
	acc.accumulate(engine.RowChange{Type: engine.RowChangeRemove, QueryID: "q1", Table: "t", RowKey: rowKey})

	got, ok := acc.deltaHex("q1")
	if !ok {
		t.Fatal("zero delta should still be available")
	}
	if got != "0" {
		t.Fatalf("zero delta = %q, want 0", got)
	}
	all := acc.allDeltasHex()
	if all["q1"] != "0" {
		t.Fatalf("allDeltasHex()[q1] = %q, want 0", all["q1"])
	}
}

func TestRowSigAccumulatorSuppressesNonScalarQuery(t *testing.T) {
	acc := NewRowSigAccumulator()
	acc.accumulate(engine.RowChange{
		Type:    engine.RowChangeAdd,
		QueryID: "q1",
		Table:   "t",
		RowKey:  map[string]interface{}{"id": "ok"},
	})
	acc.accumulate(engine.RowChange{
		Type:    engine.RowChangeAdd,
		QueryID: "q1",
		Table:   "t",
		RowKey:  map[string]interface{}{"id": []interface{}{"bad"}},
	})

	if got, ok := acc.deltaHex("q1"); ok || got != "" {
		t.Fatalf("deltaHex for invalid query = (%q,%v), want unavailable", got, ok)
	}
	if all := acc.allDeltasHex(); all != nil {
		t.Fatalf("allDeltasHex for invalid-only touched query = %#v, want nil", all)
	}
}
